`x-portone-query-or-body` 대응
portone-io/developers.portone.io pull request #429
Opened 2024-04-22 12:55 UTC by CirnoV

closes #427 

- Astro endpoint 기능으로 트랜스폼된 api 스키마를 다운로드 받을 수 있는 정적 링크 구현
- Operation 내에 `x-portone-query-or-body` 속성의 Parameter가 있으면 언어 / 라이브러리에 따라 Body 객체를 `requestBody` 쿼리로 보내거나 GET with Body로 보내도록 구현
- API 엔드포인트 문서에 `requestBody` 관련 설명 추가

2024-04-23 10:41 UTC, XiNiHa requested changes

2024-04-23 10:41 UTC, XiNiHa commented on src/layouts/rest-api/misc/SchemaDownloadButton.tsx
> +        }
이거 이런 식으로 하기보다는 애초에 OpenAPI 스키마를 다운받을 때 정적 파일 대신 API 라우트를 거치도록 해서 [(예시)](https://github.com/portone-io/developers.portone.io/blob/main/src/pages/content-index/%5BfileName%5D.json.ts) 거기서 트랜스폼하는 게 나을 것 같아요 (웹상에 해당 스키마를 정적으로 다운받을 수 있는 링크가 있는 쪽이 나을 것 같아서)

2024-04-23 10:41 UTC, XiNiHa commented on src/layouts/rest-api/endpoint/playground/try/Req.tsx
> +                  .exhaustive();
1. ts-pattern 안 쓰고 삼항연산자만 써도 충분할듯요
2. query에 body를 담을 때는 `requestBody`라는 필드 하위에 객체 형태로 담겨야 합니다
3. 이런 식으로 보낼 때만 연결해서 보내도록 하면 문서랑 Try 섹션에는 여전히 `requestBody` 쿼리 파라미터가 남겨져 있게 되는데, 이것도 처리해주셔야 해요 (스샷 참고)
4. 나중에 가면 `requestBody` 쿼리 파라미터를 가지면서 동시에 일반적인 쿼리 파라미터를 가지는 엔드포인트가 생길 수도 있어서 요것도 고려해서 `reqQueryParams` 통째로 날리는 대신 `requestBody` 속성만 추가하는 식으로 작업해주셔요

![image](https://github.com/portone-io/developers.portone.io/assets/8155259/f0408e75-f808-4e0d-a550-1ce215cf1725)

2024-04-23 10:47 UTC, CirnoV commented on src/layouts/rest-api/misc/SchemaDownloadButton.tsx
> +        }
오... Astro에 이런 기능이 있었군요. 로직만 옮기면 빠르게 수정될 것 같네요.

2024-04-23 10:55 UTC, CirnoV commented on src/layouts/rest-api/endpoint/playground/try/Req.tsx
> +                  .exhaustive();
1. 그러면 기존 query에 body 객체가 담긴  `requestBody` 필드를 추가하고
2. query 에디터에서 `requestBody`가 보이지 않게 하는 방향으로 구현하면 될까요?

2024-04-23 11:03 UTC, XiNiHa commented on src/layouts/rest-api/endpoint/playground/try/Req.tsx
> +                  .exhaustive();
음 선택지가 이렇게 있을 것 같은데...

- query 문서와 에디터에 `requestBody` 필드 표시하기, body 에디터 숨기기
  - 장점: 실제 동작을 가장 잘 나타냄
  - 단점: 시각적으로 불편함, query or body 관련 문서 작성 및 body 스키마를 `query.requestBody`에 연결시켜주는 처리 (query 에디터 내 자동완성 및 validation용) 필요
- query 문서와 에디터에서 `requestBody` 필드만 제거 (이외 필드 없으면 숨기기), body 에디터 내용 요청 실행 시에 `query.requestBody` 하위로 이동시켜서 실행
  - 장점: 시각적으로 깔끔함, 상대적으로 스키마 처리가 간편함 (쿼리 파라미터 JSON에서 `requestBody`만 날려 주면 됨)
  - 단점: 사용자가 UI를 보고 예상하는 동작과 실제 동작이 다름, query or body 관련 설명을 넣을 위치가 마땅치 않음

어느 쪽이 더 마음에 드시나요?

2024-04-23 15:11 UTC, XiNiHa requested changes

2024-04-23 15:11 UTC, XiNiHa commented on src/pages/api/schema/[version].openapi.json.ts
> +    v2: "https://raw.githubusercontent.com/portone-io/developers.portone.io/main/src/schema/v2.openapi.json",
이거 다운로드해서 트랜스폼하도록 하지 마시고, JSON import 활용하든 `node:fs` 사용해서 읽어오든 하는 게 나을 것 같아요

2024-04-24 10:06 UTC, CirnoV commented on src/pages/api/schema/[version].openapi.json.ts
> +    v2: "https://raw.githubusercontent.com/portone-io/developers.portone.io/main/src/schema/v2.openapi.json",
JSON import해서 미리 트랜스폼 해두는 방식으로 바꿨어요

2024-04-24 11:39 UTC, CirnoV commented on src/layouts/rest-api/endpoint/playground/try/Req.tsx
> +                  .exhaustive();
[슬랙에서 논의한대로](https://portone-io.slack.com/archives/C03N8773P1A/p1713870427508849?thread_ts=1713870240.805899&cid=C03N8773P1A) 후자로 구현

2024-04-25 03:50 UTC, XiNiHa commented on src/pages/api/schema/[version].openapi.json.ts
> +  if (!schema) return redirect("/404");
```suggestion
  if (!schema) return new Response(null, { status: 404 })
```
이렇게 해 둬야 나중에 404 일괄적으로 처리하기 편할 것 같아요

2024-04-25 03:50 UTC, XiNiHa commented on src/layouts/rest-api/schema-utils/operation.ts
>  }
(아마 그럴 일은 없을 것 같긴 하지만) 혹시 모르니 방어적 코딩 관점에서 query or body 여부를 파라미터로 전달받고 해당 파라미터 따라서 필터링 실행 여부 나누는 게 어떨까요?

2024-04-25 07:13 UTC, CirnoV commented on src/pages/api/schema/[version].openapi.json.ts
> +  if (!schema) return redirect("/404");
아 다른것들도 이렇게 404 처리하고 있군요

2024-04-25 07:16 UTC, CirnoV commented on src/layouts/rest-api/schema-utils/operation.ts
>  }
네 좋습니다

2024-04-25 09:40 UTC, CirnoV commented
`requestBody` 설명까지 구현하고 다시 리뷰 요청 드릴께요

2024-04-25 13:07 UTC, XiNiHa approved these changes

2024-04-25 13:24 UTC, merged