관리자콘솔 관련 내용 수정
portone-io/developers.portone.io pull request #433
Opened 2024-04-26 14:21 UTC by sso-ashley

2024-05-02 07:08 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **고객 이름** : 고객 이름 (`customer.fullname`) 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
그냥 name 아닌가요?

2024-05-02 07:21 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +  카드 번호의 경우 결제대행사에 따라 마스킹되는 부분이 다르므로, 앞에 6\~8자리(BIN)번호 혹은 뒷 4자리로 검색하시길 권장드립니다.
\ 오타인가요?

2024-05-02 07:30 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **카드사 승인번호** : 카드사 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
apply_num 인거 같은데 적어주지 않은 이유가 있나요?

2024-05-02 07:30 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **카드사 승인번호** : 카드사 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
method.approvalNum 인거 같은데 적어주지 않은 이유가 있나요?

2024-05-02 07:34 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +- **결제대행사 승인번호** : 결제대행사(PG사) 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
필드명 일부만 작성한거 같은데 기준이 있나요?

2024-05-02 07:34 UTC, sso-ashley commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **고객 이름** : 고객 이름 (`customer.fullname`) 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
주문명 V2는 orderName 맞아요 이거 versiongate 에 따라 v1/v2 일 때 다르게 보여요

2024-05-02 07:35 UTC, sso-ashley commented on src/content/docs/ko/console/guide/payments.mdx
> +  카드 번호의 경우 결제대행사에 따라 마스킹되는 부분이 다르므로, 앞에 6\~8자리(BIN)번호 혹은 뒷 4자리로 검색하시길 권장드립니다.
저거 린트돌리면 기호 앞에 \ 이거 자동으로 붙어요. 실제 페이지로 보면 안보일거에요

2024-05-02 07:35 UTC, sso-ashley commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **카드사 승인번호** : 카드사 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
apply_num 은 응답 파라미터라 안적었어요. 저거 적은거 요청파라미터 기준으로 적은거라.. 사실 추가해도 크게 상관 없을듯

2024-05-02 07:35 UTC, sso-ashley commented on src/content/docs/ko/console/guide/payments.mdx
> +    - **카드사 승인번호** : 카드사 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
위와 동일함!

2024-05-02 07:35 UTC, sso-ashley commented on src/content/docs/ko/console/guide/payments.mdx
> +- **결제대행사 승인번호** : 결제대행사(PG사) 승인번호 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다.
요청파라미터 위주로 작성했어요!

2024-05-02 07:35 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +- **결제환경** : 결제환경(PC/MOBILE/API) 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다. 검색하는 경우 대문자로 검색해야 합니다.
결제환경 상세는 없던데 삭제할 필터들은 제외한걸까요?

2024-05-02 07:37 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +- **결제환경** : 결제환경(PC/MOBILE/API) 데이터 중 입력한 텍스트와 일치하는 데이터가 표시됩니다. 검색하는 경우 대문자로 검색해야 합니다.
제외하신거네용

2024-05-02 07:39 UTC, XiNiHa commented on src/content/docs/ko/console/guide/payments.mdx
> +  카드 번호의 경우 결제대행사에 따라 마스킹되는 부분이 다르므로, 앞에 6\~8자리(BIN)번호 혹은 뒷 4자리로 검색하시길 권장드립니다.
(마크다운에서 ~가 취소선 적용할 때 쓰는 기호라서 이스케이프 처리 들어간 거에요)

2024-05-02 07:54 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +  - **휴대폰 소액결제** : 결제 요청 시 결제 수단을 휴대폰 소액결제 (`pay_method : phome`)로
phone 오타

2024-05-02 07:57 UTC, highright96 commented on src/content/docs/ko/console/guide/payments.mdx
> +      해피머니로 진행된 거래 건만 표시됩니다.
payMethod 전부 GIFT_CERTIFICATE로 변경

2024-05-02 08:09 UTC, highright96 commented on src/content/docs/ko/console/guide/billing-payments.mdx
> +- **해지** : 해지 (status : Revoked) 상태인 거래 건만 표시됩니다.
Rescheduled, RetrySucceeded, RetryFailed 상세 상태라서 제거하는건 어떨까요?

2024-05-02 08:11 UTC, highright96 commented on src/content/docs/ko/console/guide/billing-payments.mdx
> +    - 비 인증 결제(빌링키) API(Again API)를 이용한 결제 건 중 정상적으로 결제가 진행되어 결제 성공 상태인 겨래 건입니다.
겨레 -> 거래

2024-05-02 08:12 UTC, highright96 commented on src/content/docs/ko/console/guide/billing-payments.mdx
> +    - 비 인증 결제(빌링키) API(Again API)를 이용한 결제 건 중 정상적으로 결제가 진행되어 결제 성공 상태인 겨래 건입니다.
겨레로 쓴 오타가 몇 개 더 있습니다. 코멘트는 남기지 않겠습니다

2024-05-02 09:14 UTC, XiNiHa requested changes

2024-05-02 09:14 UTC, XiNiHa commented on src/content/docs/ko/console/guide/payments.mdx
> +- **결제 취소** : **전체 취소** (status : CANCELLED) 맟 **부분 취소** (PARTIAL\_CANCELLED) 상태인 거래 건만 표시됩니다.
```suggestion
- **결제 취소** : **전체 취소** (status : CANCELLED) 및 **부분 취소** (PARTIAL\_CANCELLED) 상태인 거래 건만 표시됩니다.
```

2024-05-02 09:14 UTC, XiNiHa commented on src/content/docs/ko/console/guide/payments.mdx
> +  - 승인 대기 상태는 페이팔(SRT/RT) 거래 건에서만 발생하며, 결제 및 환불 요청 완료 후 실제 승인되기까지 결제상태를 의미합니다.
```suggestion
  - 승인 대기 상태는 페이팔(SPB/RT) 거래 건에서만 발생하며, 결제 및 환불 요청 완료 후 실제 승인되기까지 결제상태를 의미합니다.
```

2024-05-02 09:14 UTC, XiNiHa commented on src/content/docs/ko/console/guide/payments.mdx
> +      (`payMethod : giftCertificate`, `giftCertificate.giftCertificateType :CULTURELAND`)로 지정하여 호출한 뒤
```suggestion
      (`payMethod : giftCertificate`, `giftCertificate.giftCertificateType : CULTURELAND`)로 지정하여 호출한 뒤
```

2024-05-02 09:14 UTC, XiNiHa commented on src/content/docs/ko/console/guide/reg.mdx
> +- `개발 연동 테스트` 를 누르면 `결제 연동`페이지로 이동합니다.
```suggestion
- `개발 연동 테스트` 를 누르면 `결제 연동` 페이지로 이동합니다.
```

2024-05-02 09:14 UTC, XiNiHa commented on src/content/docs/ko/console/guide/reg.mdx
> +- `시작하기`를 누르면 `비즈니스 인증`페이지로 이동합니다.
```suggestion
- `시작하기`를 누르면 `비즈니스 인증` 페이지로 이동합니다.
```

2024-05-08 06:57 UTC, CirnoV approved these changes

2024-05-08 07:02 UTC, XiNiHa approved these changes
내용 검수는 일단 스킵할게요

2024-05-08 07:02 UTC, merged