Release/240704
portone-io/developers.portone.io pull request #533
Opened 2024-06-27 09:25 UTC by sso-ashley

2024-06-27 10:03 UTC, CirnoV requested changes

2024-06-27 10:03 UTC, CirnoV commented on src/content/release-notes/api-sdk/2024-06-20.mdx
> +빌링키 다건조회 API에 대한 자세한 내용은 [빌링키 다건조회 API](http://developers.portone.io/api/rest-v2/billingKey?v=v2)에서
```suggestion
빌링키 다건조회 API에 대한 자세한 내용은 [빌링키 다건조회 API](/api/rest-v2/billingKey?v=v2)에서
```

2024-06-27 10:03 UTC, CirnoV commented on src/content/release-notes/api-sdk/2024-07-04.mdx
> +
여기 오류나는데 린터 한번 돌려주시면 됩니다!

2024-06-28 01:53 UTC, sso-ashley commented
@CirnoV 2024-06-20 파일은 다른 브랜치에 있는건데.. 여기에 같이 있어도 괜찮을까요? 물론 06-20 파일이 머전 머지될 예정이긴 합니다!

2024-06-28 02:12 UTC, CirnoV commented
그쪽 PR이 먼저 머지되는거면 상관없어요! 충돌은 나긴 할텐데 그건 여기서 처리해주면 돼요

2024-07-01 02:25 UTC, CirnoV approved these changes

2024-07-08 02:45 UTC, merged