개발자센터 리뉴얼 - 레이아웃 변경
portone-io/developers.portone.io pull request #589
Opened 2024-08-12 07:43 UTC by BaekGeunYoung

지난 논의 내용대로 개발자센터의 전체적인 레이아웃을 변경합니다. 기존의 `docs` 디렉토리는 건드리지 않고 `opi` 디렉토리를 새로 만들어서 여기에다 리뉴얼된 레이아웃을 구현했습니다.

2024-08-20 04:32 UTC, BaekGeunYoung commented on packages/lint-local-links-valid/src/remark.ts
> +              path.isAbsolute(link) && !link.startsWith("/api")
> 또한 기존 V1 페이지의 LNB에 존재하던 API 링크들은 /api/rest-v1/~~으로 리다이렉트만 시켜줄 뿐이어서 이번 PR에서 삭제했는데 지금 빼버려도 문제가 없을지 의견주시면 좋을 것 같습니다.

요거랑 관련 있는 부분인데, ContentRef의 slug를 `/api/rest-${version}`으로 변경하니까 lint 돌릴 때 이 경로들을 `/opi/api/rest-${version}`으로 인식해서 예외 케이스를 하나 추가해주었습니다!

2024-08-20 04:57 UTC, BaekGeunYoung commented on src/layouts/gnb/Dropdown.tsx
@CirnoV link Accessor를 Show 안에서 다시 한 번 사용할 때 smart casting은 안되어서 non-null assertion을 넣어주었는데, 이렇게 하는게 맞을지 확인 한 번 부탁드립니다!

2024-08-20 07:34 UTC, CirnoV requested changes

2024-08-20 07:34 UTC, CirnoV commented on src/layouts/gnb/Dropdown.tsx
> +        </A>
이렇게 하시면 될 것 같아요!

```suggestion
        {(link) => (
          <A class="h-full inline-flex items-center" href={link()}>
            {" "}
            {props.children}{" "}
          </A>
        )}
```

2024-08-20 07:34 UTC, CirnoV commented on src/layouts/gnb/Dropdown.tsx
[여기 코멘트](https://github.com/portone-io/developers.portone.io/pull/589#discussion_r1722830783) 남겼습니다!

2024-08-20 14:01 UTC, CirnoV approved these changes
일단 mdx 문서는 너무 많아서 확인하기가 어렵고, 그 외에 컴포넌트나 레이아웃, 구조적인 부분은 문제 없어 보입니다 👍

2024-08-21 14:00 UTC, sso-ashley approved these changes

2024-08-21 15:00 UTC, merged