결제창 호출 시 PG 파라미터를 모두 channelKey 파라미터로 대체
portone-io/developers.portone.io pull request #628
Opened 2024-09-30 03:08 UTC by SonnySon17

pg 파라미터를 deprecate 시키기 위해 결제창 호출시 예제에서의 pg 파라미터를 모두 channelKey 파라미터로 대체, 파라미터 설명에 channelKey 파라미터를 추가하고 pg 파라미터는 deprecated됨을 명시하였습니다.

2024-09-30 06:25 UTC, CirnoV requested changes

2024-09-30 06:25 UTC, CirnoV commented on src/routes/(root)/opi/ko/extra/promotion/integration.mdx
여기 `SDK(결제창) 인증결제 연동하기 > 주요 파라미터` 에 다른것들처럼 channelKey랑 pg 파라미터 설명 추가해주시면 좋을 것 같아요

2024-09-30 06:25 UTC, CirnoV commented on src/routes/(root)/opi/ko/integration/pg/v1/blue.mdx
> +    **`pg` (deprecated)** <mark style="color:green;">**string**</mark>
이렇게 대체할 파라미터를 표시해주는건 어떨까요? 만약 이렇게 바꾸시면 다른 pg사 연동 페이지에 있는 것들도 바꿔주시면 될 것 같아요

```suggestion
    **`pg` (deprecated)** <mark style="color:green;">**string**</mark>
    
    <Hint style="warning">
      pg 파라미터는 지원 중단 예정입니다. JS SDK를 가장 최신 버전으로 업그레이드 후 `channelKey` 파라미터로 채널 설정(PG사 구분)을 대체해주세요.
    </Hint>
```

2024-10-14 09:53 UTC, SonnySon17 commented on src/routes/(root)/opi/ko/integration/pg/v1/blue.mdx
> +    **`pg` (deprecated)** <mark style="color:green;">**string**</mark>
pg 파라미터 설명 있는 곳들에 hint로 말씀하신 것 처럼 표시해두었습니다.

2024-10-14 12:56 UTC, CirnoV approved these changes

2024-10-16 07:38 UTC, merged