파트너 정산 릴리즈 노트 12-05
portone-io/developers.portone.io pull request #700
Opened 2024-12-09 03:44 UTC by kdino

2024-12-09 03:51 UTC, CirnoV requested changes

2024-12-09 03:51 UTC, CirnoV commented on src/routes/(root)/release-notes/(note)/platform/2024-12-05.mdx
> +import Image2 from "./_assets/2024-12-05/screenshot2.png";
```suggestion
import Image2 from "./_assets/2024-12-05/screenshot2.jpg";
```

2024-12-09 05:06 UTC, CirnoV approved these changes

2024-12-10 09:28 UTC, kdino commented
@CirnoV 요번 문서에는 헤딩이 ### 부터 시작해서 lint에러가 나는데 요거 어떻게 해결하면 좋을까요?!

2024-12-10 09:42 UTC, CirnoV commented
@kdino 저희가 문서 스타일을 통일하기 위해 린트 규칙을 만든거여서 이것만 예외로 하기는 어렵고, 상단에 `## 주요 업데이트 사항` 문구를 추가해줘야 할 것 같아요.

2024-12-10 09:48 UTC, CirnoV approved these changes

2024-12-11 04:10 UTC, merged