웹훅 ip 화이트리스트 및 수신에 대한 정보 업데이트
portone-io/developers.portone.io pull request #71
Opened 2023-06-27 09:49 UTC by moonjihae

Outbound IP(NAT IP) 변경으로 인한 웹훅 장애 이후 개발자센터 내 웹훅 연동 안내문서를 수정하였습니다.
[참고 노션] (https://www.notion.so/chaifinance/2720e7c4b86346ee8f75e76b41e3e3ec?pvs=4)

수정 내용
* 웹훅 요청 검증하기 세션에 결제내역 단건조회 API 통해 조회 후 저장 (웹훅을 수신받지 못 한 경우에도) 하도록 안내 문구 추가
* ip 화이트 리스트는 `details` 태그 이용해 전체보기에서 숨기고  필요한 가맹점만 참고용으로 사용하고, 반드시  결제내역 단건조회 API 통해 조회 후 저장 하도록 안내 문구 추가
* 네트워크 상 문제로 웹훅이 재발송 될 수 있으니 멱등성을 보장도록 처리 권장 문구 추가

2023-06-27 11:00 UTC, XiNiHa commented on src/content/docs/ko/result/webhook.mdx
> +반드시 [결제내역 단건조회 API](../api/payment-api/get-payment-by-impuid-api)를 통해 결제건을 조회하여 검증 후 결제건을 처리해주세요.
```suggestion
포트원 웹훅은 다음의 세 가지 고정된 IP으로 요청이 생성됩니다. IP 확인은 필수가 아니므로 필요하신 가맹점에서만 참고용으로만 사용해 주시고
반드시 [결제내역 단건조회 API](../api/payment-api/get-payment-by-impuid-api)를 통해 결제건의 정보를 조회하여 검증 후 결제건을 처리해 주세요.
```

2023-06-27 14:58 UTC, simnalamburt requested changes
문장을 좀 다듬었습니다. “재시도” 에 관한 문서도 고쳐야할거같은데 그건 없던가요?

2023-06-27 14:58 UTC, simnalamburt commented on src/content/docs/ko/result/webhook.mdx
> +<b>가맹점 서버는 웹훅을 수신하고 반드시 [결제내역 단건조회 API](../api/payment-api/get-payment-by-impuid-api)를 통해 결제건을 조회하여 검증 후 저장할 수 있습니다.</b>
> 가맹점 서버는 웹훅을 수신하고 반드시 결제내역 단건조회 API를 통해 결제건을 조회하여 검증 후 저장할 수 있습니다.

문장 주술호응이 안맞아서 “(전략) 웹훅을 수신하고 반드시 결제내역 단건조회 API를 통해 결제건을 조회하여 상태를 검증해야합니다” 이런식으로 고쳐주세요. 그리고 왜 웹훅을 그대로 쓰면 안되고 단건조회를 또 때려야하는지 이유를 써줘야할거같습니다. (웹훅은 공개되어있어서 아무나 찌를 수 있다)

2023-06-27 14:58 UTC, simnalamburt commented on src/content/docs/ko/result/webhook.mdx
> +네트워크 상의 문제로 웹훅을 수신받지 못 한 경우에도 [결제내역 단건조회 API](../api/payment-api/get-payment-by-impuid-api)를 통해 결제건을 상태를 조회 후 결제건을 처리해주시길 바랍니다.
좀더 구체적으로 써야할거같아요.

“결제가 정상적으로 성공하였지만, 네트워크 문제 등의 이유로 웹훅을 수신받지 못하거나 늦게 수신받는 경우가 있을 수 있습니다. 웹훅이 오지 않거나 늦는 경우에 결제건을 바로 취소하시면 네트워크 문제가 발생했을때에 정상적인 결제건을 환불시켜버려서 금전피해가 발생할 수 있습니다. 웹훅이 안오는 경우에도 결제취소를 하기 이전에 단건조회 API를 사용해 결제건 상태를 조회하여, 결제상태가 정상적이라면 취소를 하지 말아주세요.” 이런식으로 읽는 입장에서 이해되게 써주세요.

2023-06-27 14:58 UTC, simnalamburt commented on src/content/docs/ko/result/webhook.mdx
> +웹훅 수신 후 가맹점에서는 정상 응답을 하였으나 네트워크 상의 문제로 웹훅의 response가 포트원 서버로 도달하지 않아 웹훅이 재발송 될 수 있으니, 멱등성을 보장하여 처리해주시길 권장드립니다.
그냥 멱등성이라고 하지 말고 오늘 회고에서 제가 가맹점에게 어떤식으로 설명해야한다고 디테일하게 이야기를 했었는데 그런식으로 설명해주세요. (클라이언트의 웹훅 response가 네트워크 문제로 포트원에 도달하지 않는경우 웹훅이 재시도될 수 있다. 그런경우 가맹점이 웹훅을 두번받아도 문제가 생기지 않도록 짜주시면 좋다, 멱등성이 보장된다면 제일 좋다, 등)

2023-06-27 14:58 UTC, simnalamburt commented on src/content/docs/ko/result/webhook.mdx
> +포트원 웹훅은 다음의 세 가지 고정된 IP으로 요청이 생성됩니다. IP확인은 필수가 아니므로 필요하신 가맹점에서만 참고용으로만 사용해주시고
포트원 웹훅은 다음의 세 가지 고정된 IP으로 요청이 생성됩니다 -> 포트원의 결제 웹훅은 다음의 IP주소로부터 발송됩니다.

IP확인은 필수가 아니므로 필요하신 가맹점에서만 참고용으로만 사용해주시고 반드시 [결제내역 단건조회 API](../api/payment-api/get-payment-by-impuid-api)를 통해 결제건을 조회하여 검증 후 결제건을 처리해주세요.  -> Inbound 요청에 방화벽 규칙을 설정해야 하는 등 필요한 경우에 한해 사용해주세요.

2023-06-30 02:02 UTC, simnalamburt requested changes
https://developers.portone.io/docs/ko/result/webhook 여기에도 네트워크 에러와 50x에서만 재시도를 하고 2xx-4xx에선 안한다고 써주세요

2023-06-30 02:02 UTC, simnalamburt commented on src/content/docs/ko/result/webhook.mdx
> +웹훅 수신 후 가맹점 서버에서 정상 응답을 한 경우에도 네트워크 상의 문제로 웹훅의 response가 포트원 서버로 도달하지 않아 웹훅이 재발송 될 수 있습니다.
재시도를 설정한 경우에만 재발송된다고 써야할거같아요

2023-06-30 02:23 UTC, moonjihae commented on src/content/docs/ko/result/webhook.mdx
> +웹훅 수신 후 가맹점 서버에서 정상 응답을 한 경우에도 네트워크 상의 문제로 웹훅의 response가 포트원 서버로 도달하지 않아 웹훅이 재발송 될 수 있습니다.
이것도 추가했습니다.

2023-06-30 03:10 UTC, simnalamburt approved these changes

2023-06-30 05:58 UTC, disjukr commented
이거 브랜치 이름에 `.`이 들어가서 그런지 로컬에 클론이 안되네요(...) 
![image](https://github.com/portone-io/developers.portone.io/assets/690661/27bcb5e0-f19c-4639-8de9-fbb5b5f1d139)

2023-06-30 05:59 UTC, disjukr approved these changes

2023-06-30 06:06 UTC, merged

2023-06-30 06:06 UTC, moonjihae commented
> 이거 브랜치 이름에 `.`이 들어가서 그런지 로컬에 클론이 안되네요(...) ![image](https://user-images.githubusercontent.com/690661/250007573-27bcb5e0-f19c-4639-8de9-fbb5b5f1d139.png)

앗 docs 뒤에 .이 오타로 붙었네요 월요일에 작업 할 땐 브랜치명 변경 하겠습니다!